<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260817195711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trusted_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(32) NOT NULL, validator_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F37E8F7B9692E25D ON trusted_device (selector)');
        $this->addSql('CREATE INDEX IDX_F37E8F7B9B6B5FBA ON trusted_device (account_id)');
        $this->addSql('ALTER TABLE trusted_device ADD CONSTRAINT FK_F37E8F7B9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trusted_device DROP CONSTRAINT FK_F37E8F7B9B6B5FBA');
        $this->addSql('DROP TABLE trusted_device');
    }
}
